#!/bin/bash

badge() {
  pkg=$1
  cov=$2
  echo "|$pkg|[$cov](https://gocover.io/github.com/toqoz/$pkg)|"
}
export -f badge

echo "|package|coverage|"
echo "|-------|--------|"
GOPWT_OFF=1 go test github.com/ToQoz/gopwt/... -covermode=count | grep coverage | awk -F' ' '{print $2 " " $5}' | sed -e 's,github.com/ToQoz/,,' | xargs -I{} bash -c "badge {}"
