#!/bin/sh

set -e

cwd=$(pwd)
tmpdir=$(mktemp -d)

cleanup() {
  retval=$?
  rm -rf $tmpdir
  exit $retval
}
trap cleanup INT QUIT TERM EXIT

t() {
  GOPATH=$tmpdir/$1

  pkgpath=$GOPATH/src/github.com/ToQoz/gopwt

  cd $cwd
  eval "$(gimme $1)"
  mkdir -p $pkgpath
  cp -R ./* $pkgpath/
  cd $pkgpath
  go get ./...
  go build
  ./gopwt ./...
}

t 1.5
t 1.6
