language: go
go:
  - 1.7
  - 1.8
  - 1.9
  - "1.10"
  - tip
sudo: false
before_script:
  - go get -v ./...
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
script:
  - make test-integration
  - if go get -u golang.org/x/lint/golint; then make lint; fi
  - if [[ "$TRAVIS_GO_VERSION" =~ ^1\.10 ]]; then GOPWT_OFF=1 go test -race -coverprofile=coverage.txt -covermode=atomic ./...; fi
after_success:
  - if [[ "$TRAVIS_GO_VERSION" =~ ^1\.10 ]]; then bash <(curl -s https://codecov.io/bash); fi
branches:
  only:
    # branchs through PR are built
    - master
    - travis-debug
