language: go
go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - "1.10"
  - tip
sudo: false
before_script:
  - go get -v ./...
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
script:
  - make test
  - if [[ "$TRAVIS_GO_VERSION" =~ ^1\.10 ]]; then GOPWT_OFF=1 go test -race -coverprofile=coverage.txt -covermode=atomic ./...; fi
after_success:
  - if [[ "$TRAVIS_GO_VERSION" =~ ^1\.10 ]]; then bash <(curl -s https://codecov.io/bash); fi
notifications:
  email:
    recipients:
      - toqoz403@gmail.com
    on_success: change
    on_failure: always
