language: go
go:
  - 1.2
  - 1.3
  - 1.4.1
  - 1.5
  - 1.6
  - tip
sudo: false
before_script:
  - go get -v ./...
script:
  - make test
  - curl https://gocover.io/github.com/toqoz/gopwt
  - curl https://gocover.io/github.com/toqoz/gopwt/assert
  - curl https://gocover.io/github.com/toqoz/gopwt/translatedassert
notifications:
  email:
    recipients:
      - toqoz403@gmail.com
    on_success: change
    on_failure: always
