language: go
go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - tip
sudo: false
before_script:
  - go get -v ./...
script:
  - make test
notifications:
  email:
    recipients:
      - toqoz403@gmail.com
    on_success: change
    on_failure: always
