version: "{build}"

clone_folder: c:\gopath\src\github.com\ToQoz\gopwt

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env

deploy: false
build: false

test_script:
  - go get -v ./...
  - go test -v ./...
